### ISSUE TITLE
Error creating new organisation

### ISSUE THREAD

**Issue by stkenny** [Digital-Repository-of-Ireland/dri-app#8]
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"institutes", :id=>#<Institute id: nil, name: "xxxxx", url: "xxxx", created_at: nil, updated_at: nil, logo: nil, depositing: true>}, possible unmatched constraints: [:id]
Did you mean?  organisations_url
               organisation_path
               organisations_path
               edit_organisation_url

**Comment by MuriloDiasTCD** [comment]
Hi Stuart,
Is there a way to simulate this error in my local environment ?

The checks that I implement before compose the link are:
`@document.has_aggregation_data? && @document.public_read? && !@assets.empty? && @document.valid_edm?`

Do you believe a check to validate if depositing organization empty would solve that ?

**Comment by MuriloDiasTCD** [comment]
I'm wondering if the logical test `!@assets.empty?` could return 'NoMethodError' as per [this table](https://medium.com/le-wagon/how-to-use-nil-blank-present-exists-in-rails-5-fe03e78ab979#:~:text=Check%20out%20my,the%20full%20article%20%3B)

Other justification for this error could be `./app/views/shared/_tools.html.erb` being used in other if not related to assets, so the checks could not access assets and lead to some kind of unexpected error. 

I keep investigating from my side.
